server:
  port: 9122
  servlet:
    context-path: /
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver
    username: study
    password: study
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.yidu.businessParameter.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl